name: Autocloser
on: [pull_request]
jobs:
  autoclose:
    runs-on: ubuntu-24.04
    steps:
    - name: Autoclose prs that did not follow pr template
      uses: roots/issue-closer@v1.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-close-message: "This PR was automatically closed because it did not use the PR template. This is usually because it has been filled with automated tools, which are causing large volumes of spam to this repository. Please re-file the PR by hand."
        pr-pattern: ".*my pull request fulfills the criteria therein.*"
