name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-md:
    runs-on: ubuntu-24.04
    name: Lint Markdown content
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
      - name: Markdown lint for README
        uses: docker://avtodev/markdown-lint:v1
        with:
          config: ./.markdownlint.json
          args: ./README.md

  lint-editorconfig:
    runs-on: ubuntu-24.04
    name: Lint for editorconfig violations
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
      - name: Check for editorconfig violations
        uses: editorconfig-checker/action-editorconfig-checker@v3.0.0

  lint-markdown-toc:
    runs-on: ubuntu-24.04
    name: Lint for Table of Contents
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
      - name: Download mktoc
        run: |
          wget https://github.com/KevinGimbel/mktoc/releases/download/v5.1.1/mktoc-x86_64-unknown-linux-gnu.tar.gz
          tar -zxvf mktoc-x86_64-unknown-linux-gnu.tar.gz
      - run: ./mktoc README.md
      - run: git diff --exit-code
